apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-backend
  namespace: devops-cicd
spec:
  provider: azure
  parameters:
    usePodIdentity:        "false"
    useVMManagedIdentity:  "true"
    cloudName:             ""
    userAssignedIdentityID: {{ .Values.clientId }}
    tenantId:              {{ .Values.tenantId }}
    keyvaultName:          {{ .Values.keyvaultName }}
    objects: |
      array:
        - |
          objectName: "postgresql-admin-password"
          objectType: secret
          objectVersion: ""
