apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-backend
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ .Values.keyvaultName }}
    tenantId: {{ .Values.tenantId }}
    objects: |
      array:
        - |
          objectName: DB_HOST
          objectType: secret
        - |
          objectName: DB_USER
          objectType: secret
        - |
          objectName: DB_PASSWORD
          objectType: secret
