apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-backend
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.clientId }}
    keyvaultName: {{ .Values.keyvaultName }}
    tenantId: {{ .Values.tenantId }}
    objects: |
      - objectName: "postgresql-admin-password"
        objectType: "secret"
