apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  selector:
    app: {{ include "backend.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
