replicaCount: 1

image:
  repository: ghcr.io/your-org/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  POSTGRES_HOST: ""
  POSTGRES_PORT: "5432"
  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
