name: CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Get secrets from Key Vault
        uses: azure/cli@v2
        with:
          inlineScript: |
            az keyvault secret show --vault-name ${{ secrets.KEYVAULT_NAME }} --name <SECRET_NAME>

      - name: Helm Deploy Backend
        run: |
          helm upgrade --install backend ./helm/backend --set image.tag=latest

      - name: Helm Deploy Frontend
        run: |
          helm upgrade --install frontend ./helm/frontend --set image.tag=latest

      - name: Install dependencies for E2E
        run: |
          cd e2e/playwright
          npm ci

      - name: Run Playwright E2E tests
        env:
          PLAYWRIGHT_BASE_URL: ${{ steps.get_frontend_url.outputs.url }}
        run: |
          cd e2e/playwright
          npx playwright test

      - name: Notify
        run: echo "Send notification here"

      - name: Generate Badges
        run: echo "Generate badges here"

      - name: Get Frontend URL
        id: get_frontend_url
        run: echo "url=https://frontend.example.com" >> $GITHUB_OUTPUT
