name: Helm Deploy

on:
  push:
    branches: [ staging ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (e.g., prod)"
        required: true
        default: "prod"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: devops-cicd
      ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_github_username: ${{ secrets.TF_VAR_GITHUB_USERNAME }}
      TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Assign Managed Identity to VMSS
      run: |
        # Variables
        RESOURCE_GROUP="rg-devops-cicd-${{ env.ENVIRONMENT }}"
        AKS_CLUSTER_NAME="aks-devops-cicd-${{ env.ENVIRONMENT }}"
        CLIENT_ID="${{ env.ARM_CLIENT_ID }}"

        # Récupérer le nom du nodepool (VMSS)
        NODEPOOL_NAME=$(az aks nodepool list --resource-group $RESOURCE_GROUP --cluster-name $AKS_CLUSTER_NAME --query "[0].name" -o tsv)
        VMSS_NAME="${AKS_CLUSTER_NAME}-vmss-${NODEPOOL_NAME}"

        echo "Assigning Managed Identity $CLIENT_ID to VMSS $VMSS_NAME in $RESOURCE_GROUP"
        az vmss identity assign --resource-group $RESOURCE_GROUP --name $VMSS_NAME --identities $CLIENT_ID

    - name: Set AKS context
      run: |
        az aks get-credentials \
          --resource-group rg-devops-cicd-${{ env.ENVIRONMENT }} \
          --name          aks-devops-cicd-${{ env.ENVIRONMENT }}

    - name: Prepare namespace
      run: |
        kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
        kubectl create secret docker-registry ghcr \
          --docker-server=ghcr.io \
          --docker-username=${{ secrets.TF_VAR_GITHUB_USERNAME }} \
          --docker-password=${{ secrets.TF_VAR_GITHUB_TOKEN }} \
          --namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Detect AKS KeyVault add‑on
      id: addon
      run: |
        flag=$(az aks show \
          --resource-group rg-devops-cicd-${{ env.ENVIRONMENT }} \
          --name          aks-devops-cicd-${{ env.ENVIRONMENT }} \
          --query "addonProfiles.azureKeyvaultSecretsProvider.enabled" -o tsv 2>/dev/null || echo "false")
        echo "addonEnabled=$flag" >> "$GITHUB_OUTPUT"

    - name: Uninstall legacy Helm releases
      if: steps.addon.outputs.addonEnabled == 'false'
      run: |
        helm uninstall azure-keyvault-provider -n kube-system || true
        helm uninstall csi-secrets-store   -n kube-system || true
        kubectl delete daemonset -n kube-system -l app=csi-secrets-store-provider-azure --ignore-not-found
        kubectl delete daemonset -n kube-system -l app=secrets-store-csi-driver       --ignore-not-found
        kubectl wait --for=delete pod -n kube-system -l app=csi-secrets-store-provider-azure --timeout=120s || true

    - name: Install Azure Key Vault provider (Helm)
      if: steps.addon.outputs.addonEnabled == 'false'
      run: |
        helm repo add csi-secrets-store-provider-azure \
          https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
        helm repo update
        helm upgrade --install azure-keyvault-provider \
          csi-secrets-store-provider-azure/csi-secrets-store-csi-provider-azure \
          --namespace kube-system \
          --set secrets-store-csi-driver.syncSecret.enabled=true \
          --set secrets-store-csi-driver.enableSecretRotation=true \
          --set metricsAddr="8899" \
          --wait

    - name: Wait for provider pods (if chart was installed)
      if: steps.addon.outputs.addonEnabled == 'false'
      run: |
        echo "Waiting up to 5 min for provider pods…"
        kubectl -n kube-system wait --for=condition=ready pod \
          -l app=csi-secrets-store-provider-azure \
          --timeout=300s

    - name: Helm upgrade backend
      run: |
        helm upgrade --install backend ./helm/backend \
          --set keyvaultName=kv-devops-cicd-${{ env.ENVIRONMENT }} \
          --set tenantId=${{ env.ARM_TENANT_ID }} \
          --set clientId=${{ env.ARM_CLIENT_ID }} \
          --namespace $NAMESPACE

    - name: Helm upgrade frontend
      run: |
        helm upgrade --install frontend ./helm/frontend --namespace $NAMESPACE
