name: Helm Deploy

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (e.g., prod)'
        required: true
        default: 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: devops-cicd
      ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group rg-devops-cicd-${{ env.ENVIRONMENT }} \
            --name aks-devops-cicd-${{ env.ENVIRONMENT }}

      - name: Create namespace
        run: |
          kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

      - name: Create image pull secret
        run: |
          kubectl create secret docker-registry ghcr \
            --docker-server=ghcr.io \
            --docker-username=${{ secrets.TF_VAR_GITHUB_USERNAME }} \
            --docker-password=${{ secrets.TF_VAR_GITHUB_TOKEN }} \
            --namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
      
      - name: Delete existing CSIDriver if present
        run: |
          kubectl delete csidriver secrets-store.csi.k8s.io --ignore-not-found

      - name: Install Secrets Store CSI Driver
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v1.4.0/deploy/secrets-store-csi-driver.yaml
          kubectl apply -f https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/v1.4.0/deploy/provider-azure-installer.yaml

      - name: Helm upgrade backend
        run: |
          helm upgrade --install backend ./helm/backend \
            --set imagePullSecrets[0].name=ghcr \
            --set keyvaultName=kv-devops-cicd-${{ env.ENVIRONMENT }} \
            --set tenantId=$(az account show --query tenantId -o tsv) \
            --namespace $NAMESPACE --wait

      - name: Helm upgrade frontend
        run: |
          helm upgrade --install frontend ./helm/frontend \
            --set imagePullSecrets[0].name=ghcr \
            --set keyvaultName=kv-devops-cicd-${{ env.ENVIRONMENT }} \
            --set tenantId=$(az account show --query tenantId -o tsv) \
            --namespace $NAMESPACE --wait
