name: Helm Deploy

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: 'prod'
        required: true
        default: 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group rg-devops-cicd-${{ github.event.inputs.environment }} --name aks-devops-cicd-${{ github.event.inputs.environment }}

      - name: Create image pull secret
        run: |
          kubectl create secret docker-registry ghcr \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.TF_VAR_GITHUB_TOKEN }} \
            --namespace devops-cicd --dry-run=client -o yaml | kubectl apply -f -

      - name: Helm upgrade backend
        run: |
          helm upgrade --install backend ./charts/backend \
            --set imagePullSecrets[0].name=ghcr \
            --set keyvaultName=kv-devops-cicd-${{ github.event.inputs.environment }} \
            --set tenantId=$(az account show --query tenantId -o tsv) \
            --namespace devops-cicd --wait

      - name: Helm upgrade frontend
        run: |
          helm upgrade --install frontend ./charts/frontend 
