name: Helm Deploy

on:
  push:
    branches: [ staging ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (e.g., prod)"
        required: true
        default: "prod"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: devops-cicd
      ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_github_username: ${{ secrets.TF_VAR_GITHUB_USERNAME }}
      TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}

    steps:
      # ────────── Git / AKS context ──────────
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group rg-devops-cicd-${{ env.ENVIRONMENT }} \
            --name          aks-devops-cicd-${{ env.ENVIRONMENT }}

      # ────────── Namespace & image‑pull secret ──────────
      - name: Prepare namespace
        run: |
          kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret docker-registry ghcr \
            --docker-server=ghcr.io \
            --docker-username=${{ secrets.TF_VAR_GITHUB_USERNAME }} \
            --docker-password=${{ secrets.TF_VAR_GITHUB_TOKEN }} \
            --namespace $NAMESPACE \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Install NGINX Ingress Controller
        run: |
          chmod +x ./deployment/helm/install_nginx_controller.sh
          ./deployment/helm/install_nginx_controller.sh

      - name: Install Key Vault Provider
        run: |
          chmod +x ./deployment/helm/install_keyvault_provider.sh
          ./deployment/helm/install_keyvault_provider.sh

      - name: Configure Key Vault Integration
        run: |
          KEY_VAULT_NAME=$(az keyvault list -g rg-devops-cicd-${{ github.event.inputs.environment }} --query "[0].name" -o tsv)
          TENANT_ID=$(az account show --query tenantId -o tsv)
          
          # Update Secret Provider Class with actual values
          sed -i "s/\${KEY_VAULT_NAME}/$KEY_VAULT_NAME/g" ./deployment/helm/backend/templates/secret-provider.yaml
          sed -i "s/\${TENANT_ID}/$TENANT_ID/g" ./deployment/helm/backend/templates/secret-provider.yaml

      - name: Deploy Backend
        run: |
          helm upgrade --install backend ./deployment/helm/backend \
            --namespace ${{ env.NAMESPACE }} \
            --set postgresql.host=${{ secrets.DB_HOST }} \
            --set postgresql.port=${{ secrets.DB_PORT }} \
            --set postgresql.database=${{ secrets.DB_NAME }}

      - name: Deploy Frontend
        run: |
          helm upgrade --install frontend ./deployment/helm/frontend 

      - name: Deploy Ingress
        run: |
          helm upgrade --install ingress ./deployment/helm/ingress \
            --namespace ${{ env.NAMESPACE }}

      - name: Verify deployments
        run: |
          echo "Waiting for deployments to be ready..."
          kubectl wait --for=condition=available --timeout=300s deployment/backend -n ${{ env.NAMESPACE }}
          kubectl wait --for=condition=available --timeout=300s deployment/frontend -n ${{ env.NAMESPACE }}
          
          echo "Getting service URLs..."
          BACKEND_IP=$(kubectl get svc -n ${{ env.NAMESPACE }} backend -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          FRONTEND_IP=$(kubectl get svc -n ${{ env.NAMESPACE }} frontend -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          
          echo "Backend service available at: http://$BACKEND_IP"
          echo "Frontend service available at: http://$FRONTEND_IP"
