replicaCount: 1

image:
  repository: ghcr.io/your-org/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  - name: REACT_APP_API_URL
    value: "http://backend:8000"
